# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Aaron/Desktop/HMMs/Pynq_v1/Pynq_v1.srcs/sources_1/bd/design_1/ip/design_1_HMM_Scoring_0_3/design_1_HMM_Scoring_0_3.xci
# IP: The module: 'design_1_HMM_Scoring_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaron/Desktop/HMMs/Pynq_v1/Pynq_v1.srcs/sources_1/bd/design_1/ip/design_1_HMM_Scoring_0_3/constraints/HMM_Scoring_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_HMM_Scoring_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Aaron/Desktop/HMMs/Pynq_v1/Pynq_v1.srcs/sources_1/bd/design_1/ip/design_1_HMM_Scoring_0_3/design_1_HMM_Scoring_0_3.xci
# IP: The module: 'design_1_HMM_Scoring_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaron/Desktop/HMMs/Pynq_v1/Pynq_v1.srcs/sources_1/bd/design_1/ip/design_1_HMM_Scoring_0_3/constraints/HMM_Scoring_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_HMM_Scoring_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
